on:
  push:
    branches:
      - 'master'

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror master to main
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'master'
        dest: 'main'
